// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmbKYkJi2XKHCZhcTy2e-AKSa6uFDi1g',
    appId: '1:798318890821:web:35be127248ddd0c245782c',
    messagingSenderId: '798318890821',
    projectId: 'zuma-shop',
    authDomain: 'zuma-shop.firebaseapp.com',
    storageBucket: 'zuma-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMhGUeZgP11eQbHizr8Cj304FUgfIcc_4',
    appId: '1:798318890821:android:4428bc904f123f6b45782c',
    messagingSenderId: '798318890821',
    projectId: 'zuma-shop',
    storageBucket: 'zuma-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrLRIl6iXYtXeuxWO6iVEyc3RRY0JkTw8',
    appId: '1:798318890821:ios:c3c28e5dfcb6b2e645782c',
    messagingSenderId: '798318890821',
    projectId: 'zuma-shop',
    storageBucket: 'zuma-shop.appspot.com',
    iosBundleId: 'com.example.zumasPetShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrLRIl6iXYtXeuxWO6iVEyc3RRY0JkTw8',
    appId: '1:798318890821:ios:c3c28e5dfcb6b2e645782c',
    messagingSenderId: '798318890821',
    projectId: 'zuma-shop',
    storageBucket: 'zuma-shop.appspot.com',
    iosBundleId: 'com.example.zumasPetShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEmbKYkJi2XKHCZhcTy2e-AKSa6uFDi1g',
    appId: '1:798318890821:web:a7da2854ce1c2a6245782c',
    messagingSenderId: '798318890821',
    projectId: 'zuma-shop',
    authDomain: 'zuma-shop.firebaseapp.com',
    storageBucket: 'zuma-shop.appspot.com',
  );

}